
# roles/jenkins_docker/tasks/main.yml
---
- name: Install required dependencies
  yum:
    name: 
      - git
      - yum-utils
    state: present

# Install Docker using yum package manager
- name: Add Docker repository
  yum_repository:
    name: docker
    description: Docker CE Stable - x86_64
    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    state: present

- name: Install Docker
  yum:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes
      ##########################################
- name: Add ec2-user to Docker group
  user:
    name: ec2-user
    groups: docker
    append: yes

- name: Restart Docker service
  systemd:
    name: docker
    state: restarted
  become: true

- name: Verify Docker group membership
  shell: "groups ec2-user"
  register: user_groups
  changed_when: false

- name: Display Docker group membership
  debug:
    msg: "{{ user_groups.stdout }}"

- name: Check Docker version
  command: docker --version
  register: docker_version
  changed_when: false

- name: Display Docker version
  debug:
    msg: "{{ docker_version.stdout }}"




